service: github-search
custom:
  github_token: "****************************************"
  s3-bucket-name: "github-search-vue-app"
  s3Sync:
    - bucketName: ${self:custom.s3-bucket-name}
      localDir: vue

plugins:
  - serverless-s3-sync

provider:
  profile: default
  name: aws
  memorySize: 128
  timeout: 5
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  environment:
    GITHUB_TOKEN: ${self:custom.github_token}

functions:
  find:
    handler: src/index.handler
    events:
      - http:
          path: find
          method: post
          cors: true

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.s3-bucket-name}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]